"""Custom fields that connect Smule's storefront metadata to native ERPNext records."""


def get_custom_fields():
	return {
		"Item": [
			{
				"fieldname": "smule_storefront_section",
				"fieldtype": "Section Break",
				"label": "فروشگاه اسموله",
				"insert_after": "website_description",
			},
			{
				"fieldname": "smule_enabled_in_storefront",
				"fieldtype": "Check",
				"label": "نمایش در فروشگاه اسموله",
				"default": "0",
				"insert_after": "smule_storefront_section",
			},
			{
				"fieldname": "smule_storefront_type",
				"fieldtype": "Select",
				"label": "نوع دادهٔ کوکی",
				"options": "\nProduct\nDough\nTopping\nFlavor",
				"insert_after": "smule_enabled_in_storefront",
			},
			{
				"fieldname": "smule_slug",
				"fieldtype": "Data",
				"label": "شناسهٔ فروشگاهی",
				"insert_after": "smule_storefront_type",
			},
			{
				"fieldname": "smule_display_name_fa",
				"fieldtype": "Data",
				"label": "نام فارسی در فروشگاه",
				"insert_after": "smule_slug",
			},
			{
				"fieldname": "smule_description_fa",
				"fieldtype": "Small Text",
				"label": "توضیح فارسی",
				"insert_after": "smule_display_name_fa",
			},
			{
				"fieldname": "smule_serving_description_fa",
				"fieldtype": "Data",
				"label": "اندازهٔ سرو",
				"insert_after": "smule_description_fa",
			},
			{
				"fieldname": "smule_recipe_is_sample",
				"fieldtype": "Check",
				"label": "دستور و اطلاعات غذایی نمونه و تأییدنشده است",
				"default": "0",
				"insert_after": "smule_serving_description_fa",
			},
			{
				"fieldname": "smule_category_fa",
				"fieldtype": "Data",
				"label": "دسته‌بندی فروشگاهی",
				"insert_after": "smule_description_fa",
			},
			{
				"fieldname": "smule_ingredients_fa",
				"fieldtype": "Small Text",
				"label": "مواد تشکیل‌دهنده",
				"insert_after": "smule_category_fa",
			},
			{
				"fieldname": "smule_not_included_fa",
				"fieldtype": "Small Text",
				"label": "فاقدِ موارد",
				"insert_after": "smule_ingredients_fa",
			},
			{
				"fieldname": "smule_component_group",
				"fieldtype": "Select",
				"label": "گروه افزودنی",
				"options": "\nfruit\nchocolate\nnuts\ncreams\nflavor\ncrunch\ngrains",
				"insert_after": "smule_not_included_fa",
			},
			{
				"fieldname": "smule_grams_per_50g",
				"fieldtype": "Float",
				"label": "گرم افزودنی به‌ازای بیس ۵۰ گرمی",
				"default": "0",
				"insert_after": "smule_component_group",
			},
			{
				"fieldname": "smule_base_weight_grams",
				"fieldtype": "Float",
				"label": "وزن پایه (گرم)",
				"default": "0",
				"insert_after": "smule_grams_per_50g",
			},
			{
				"fieldname": "smule_kcal_per_100g",
				"fieldtype": "Float",
				"label": "کالری تقریبی در ۱۰۰ گرم",
				"default": "0",
				"insert_after": "smule_base_weight_grams",
			},
			{
				"fieldname": "smule_protein_per_100g",
				"fieldtype": "Float",
				"label": "پروتئین در ۱۰۰ گرم",
				"default": "0",
				"insert_after": "smule_kcal_per_100g",
			},
			{
				"fieldname": "smule_carbs_per_100g",
				"fieldtype": "Float",
				"label": "کربوهیدرات در ۱۰۰ گرم",
				"default": "0",
				"insert_after": "smule_protein_per_100g",
			},
			{
				"fieldname": "smule_fat_per_100g",
				"fieldtype": "Float",
				"label": "چربی در ۱۰۰ گرم",
				"default": "0",
				"insert_after": "smule_carbs_per_100g",
			},
			{
				"fieldname": "smule_sugar_per_100g",
				"fieldtype": "Float",
				"label": "قند در ۱۰۰ گرم",
				"default": "0",
				"insert_after": "smule_fat_per_100g",
			},
			{
				"fieldname": "smule_allergens_fa",
				"fieldtype": "Small Text",
				"label": "آلرژن‌ها",
				"insert_after": "smule_sugar_per_100g",
			},
			{
				"fieldname": "smule_visual_group",
				"fieldtype": "Select",
				"label": "گروه نمایشی پیش‌نمایش",
				"options": "\nchocolate\nnut\ncrumb\nsalt",
				"insert_after": "smule_allergens_fa",
			},
			{
				"fieldname": "smule_visual_color",
				"fieldtype": "Color",
				"label": "رنگ نمایشی",
				"insert_after": "smule_visual_group",
			},
			{
				"fieldname": "smule_sort_order",
				"fieldtype": "Int",
				"label": "ترتیب نمایش",
				"default": "0",
				"insert_after": "smule_visual_color",
			},
			{
				"fieldname": "smule_storefront_end",
				"fieldtype": "Section Break",
				"label": "",
				"insert_after": "smule_sort_order",
			},
		],
		"Customer": [
			{
				"fieldname": "smule_phone_number",
				"fieldtype": "Data",
				"label": "شمارهٔ تماس اسموله",
				"insert_after": "customer_name",
				"no_copy": 1,
			},
		],
		"Sales Order": [
			{
				"fieldname": "smule_delivery_method",
				"fieldtype": "Select",
				"label": "روش دریافت اسموله",
				"options": "\nتحویل حضوری\nارسال",
				"insert_after": "customer_name",
			},
			{
				"fieldname": "smule_delivery_address",
				"fieldtype": "Small Text",
				"label": "نشانی تحویل",
				"insert_after": "smule_delivery_method",
			},
			{
				"fieldname": "smule_customer_note",
				"fieldtype": "Small Text",
				"label": "توضیحات مشتری اسموله",
				"insert_after": "smule_delivery_address",
			},
			{
				"fieldname": "smule_customer_phone",
				"fieldtype": "Data",
				"label": "شمارهٔ تماس مشتری",
				"insert_after": "smule_customer_note",
			},
			{
				"fieldname": "smule_requested_for_time",
				"fieldtype": "Time",
				"label": "ساعت ترجیحی دریافت اسموله",
				"insert_after": "delivery_date",
			},
			{
				"fieldname": "smule_delivery_latitude",
				"fieldtype": "Float",
				"label": "عرض جغرافیایی محل تحویل اسموله",
				"hidden": 1,
				"read_only": 1,
				"insert_after": "smule_requested_for_time",
			},
			{
				"fieldname": "smule_delivery_longitude",
				"fieldtype": "Float",
				"label": "طول جغرافیایی محل تحویل اسموله",
				"hidden": 1,
				"read_only": 1,
				"insert_after": "smule_delivery_latitude",
			},
		],
		"Sales Order Item": [
			{
				"fieldname": "smule_cookie_recipe_section",
				"fieldtype": "Section Break",
				"label": "ترکیب کوکی اسموله",
				"insert_after": "description",
			},
			{
				"fieldname": "smule_cookie_recipe_summary",
				"fieldtype": "Small Text",
				"label": "خلاصهٔ ترکیب",
				"insert_after": "smule_cookie_recipe_section",
			},
			{
				"fieldname": "smule_cookie_recipe_json",
				"fieldtype": "Long Text",
				"label": "دادهٔ ترکیب کوکی",
				"insert_after": "smule_cookie_recipe_summary",
			},
			{
				"fieldname": "smule_cookie_base_weight_grams",
				"fieldtype": "Float",
				"label": "وزن پایه (گرم)",
				"insert_after": "smule_cookie_recipe_json",
			},
			{
				"fieldname": "smule_cookie_final_weight_grams",
				"fieldtype": "Float",
				"label": "وزن نهایی تقریبی (گرم)",
				"insert_after": "smule_cookie_base_weight_grams",
			},
			{
				"fieldname": "smule_cookie_estimated_calories",
				"fieldtype": "Float",
				"label": "کالری تقریبی",
				"insert_after": "smule_cookie_final_weight_grams",
			},
			{
				"fieldname": "smule_cookie_quote_required",
				"fieldtype": "Check",
				"label": "نیازمند اعلام قیمت",
				"default": "0",
				"insert_after": "smule_cookie_estimated_calories",
			},
		],
	}
